### ISSUE TITLE
Отступы в начале и в конце области видимости

### ISSUE THREAD

**Issue by truenorthpaul** [AlexShyshkov/TitleCapitalizationTool#11]
В начале области видимости (после открывающейся фигурной скобки) и в конце области видимости (перед закрывающейся фигурной скобкой) не должно быть отступов в виде пустых строк.

Методы, в которых данное правило не соблюдается:
- `TitleCapitalizationTool.Program.Main`.

**Comment by AlexShyshkov** [comment]
Close#11
