### ISSUE TITLE
Сокращения в идентификаторах

### ISSUE THREAD

**Issue by truenorthpaul** [AlexShyshkov/TitleCapitalizationTool#7]
В идентификаторах не должны использоваться сокращения. Однако, допускается использование общеупотребимых аббревиатур (например, `HttpRequest`, `tcpConnection`, `GetUtcTime()`).

Переменные, для идентификаторов которых данное правило не соблюдается:
- `ch` (метод `TitleCapitalizationTool.Program.Main`).

**Comment by AlexShyshkov** [comment]
Close#7
