### ISSUE TITLE
Нарушение конвенции именования идентификаторов

### ISSUE THREAD

**Issue by truenorthpaul** [AlexShyshkov/TitleCapitalizationTool#9]
При создании идентификаторов необходимо придерживаться следующих конвенций именования:
- `camelCase` - переменные, поля, параметры.
- `PascalCase` - пространства имен, типы (классы, структуры и т.п.), методы, свойства, события.

Переменные, для которых данное правило не соблюдается:
- `WordsException` (метод `TitleCapitalizationTool.Program.Main`).

**Comment by AlexShyshkov** [comment]
Close#9

**Comment by truenorthpaul** [comment]
Члены перечисления должны использовать схему именования `PascalCase`.
